version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  localstack:
    image: localstack/localstack:0.13
    environment: 
      - AWS_DEFAULT_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - EDGE_PORT=4566
      - SERVICES=firehose,s3,iam,dynamodb
      - KINESIS_PROVIDER=kinesalite
    ports:
      - '4566:4566'