name: Run Tests (job)

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    name: ⚡ Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
                
      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Start containers
        run: docker-compose -f localDev/docker-compose.yml up -d

      - name: Unit tests
        run: npm run coverage:unit
      - name: Upload unit test coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage_unit/
          fail_ci_if_error: false
          files: ./coverage_unit/lcov.info
          flags: unittests

      - name: Integration tests
        run: npm run coverage:integration
      - name: Upload integration test coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage_integration/
          fail_ci_if_error: false
          files: ./coverage_integration/lcov.info
          flags: integrationtests

      - name: Stop containers
        if: always()
        run: docker-compose -f localDev/docker-compose.yml down