name: Run Tests (job)

on:
  workflow_call:

jobs:
  test:
    name: ⚡ Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_xapi_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: xapiserver
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
                
      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Start containers
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Run tests
        run: npm run test:ci

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.test.yml down